/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.geekmarket.arduinoconexion;

import com.panamahitek.ArduinoException;
import com.panamahitek.PanamaHitek_Arduino;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import jssc.SerialPortEvent;
import jssc.SerialPortEventListener;
import jssc.SerialPortException;

/**
 *
 * @author Arrecis
 */
public class Ventana_copia extends javax.swing.JFrame {
        int Encender;
        ImageIcon Usuario = new ImageIcon("troyano.png");
        ImageIcon IconoLavado = new ImageIcon("Lavado.png");
        ImageIcon IconoEnjuagado = new ImageIcon("Enjuagado.png");
        ImageIcon IconoSecado = new ImageIcon("Secado.png");
        ImageIcon IconoFinalizado = new ImageIcon("Finalizado.png");
        ImageIcon IconoEnjabonado = new ImageIcon("Enjabonado.png");
        ImageIcon IconoInicio = new ImageIcon("Inicio.png");
       ImageIcon IconoAvanzar = new ImageIcon("Avanzar.png");
        PanamaHitek_Arduino arduino = new PanamaHitek_Arduino();
        SerialPortEventListener escucha = new SerialPortEventListener() {
            @Override
            public void serialEvent(SerialPortEvent spe) {
                try {
                    if(arduino.isMessageAvailable()==true){
                        datoT.setText(arduino.printMessage());
                        String D= arduino.printMessage();
                        System.out.println(datoT.getText());
                        Mensaje(datoT.getText());
                    }} catch (SerialPortException ex) {
                    Logger.getLogger(Ventana_copia.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ArduinoException ex) {
                    Logger.getLogger(Ventana_copia.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        };
    
    public Ventana_copia() {
        initComponents();
        this.setTitle("Car Wash Troyans");
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        
        Icono.setIcon((new ImageIcon(Usuario.getImage().getScaledInstance(Icono.getWidth(),Icono.getHeight(),Image.SCALE_SMOOTH))));
        Imagen.setIcon((new ImageIcon(IconoInicio.getImage().getScaledInstance(Icono.getWidth(),Icono.getHeight(),Image.SCALE_SMOOTH))));
        
            try {
                arduino.arduinoRXTX("COM5", 9600, escucha);
            } catch (ArduinoException ex) {
                Logger.getLogger(Ventana_copia.class.getName()).log(Level.SEVERE, null, ex);
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        Barra = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        ejabonado = new javax.swing.JLabel();
        EnjabonadoL = new javax.swing.JLabel();
        desaguado = new javax.swing.JLabel();
        DesaguadoL = new javax.swing.JLabel();
        cepillado = new javax.swing.JLabel();
        CepilladoL = new javax.swing.JLabel();
        secado = new javax.swing.JLabel();
        SecadoL = new javax.swing.JLabel();
        finalidadoL = new javax.swing.JLabel();
        finalizado = new javax.swing.JLabel();
        Icono = new javax.swing.JLabel();
        Imagen = new javax.swing.JLabel();
        datoT = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImages(getIconImages());

        jButton1.setText("Iniciar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Barra.setFont(new java.awt.Font("Agency FB", 2, 24)); // NOI18N
        Barra.setStringPainted(true);

        jLabel1.setFont(new java.awt.Font("Agency FB", 2, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ETAPA:");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)), "Proceso de Lavado", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Agency FB", 2, 18))); // NOI18N

        ejabonado.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        ejabonado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ejabonado.setText("Enjabonado: ");

        EnjabonadoL.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        EnjabonadoL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EnjabonadoL.setOpaque(true);

        desaguado.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        desaguado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        desaguado.setText("Enjuagado");

        DesaguadoL.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        DesaguadoL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DesaguadoL.setOpaque(true);

        cepillado.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        cepillado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cepillado.setText("Lavado:");

        CepilladoL.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        CepilladoL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CepilladoL.setOpaque(true);

        secado.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        secado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        secado.setText("Secado:");

        SecadoL.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        SecadoL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SecadoL.setOpaque(true);

        finalidadoL.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        finalidadoL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        finalidadoL.setOpaque(true);

        finalizado.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        finalizado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        finalizado.setText("Finalizado:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(ejabonado, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EnjabonadoL, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(desaguado, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DesaguadoL, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cepillado, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CepilladoL, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(secado, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SecadoL, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(finalizado, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(finalidadoL, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ejabonado, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(EnjabonadoL, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cepillado, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(CepilladoL, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(desaguado, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(DesaguadoL, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(secado, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(SecadoL, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(finalizado, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(finalidadoL, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        datoT.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        datoT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(282, 282, 282)
                                .addComponent(jButton1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(95, 95, 95)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addComponent(Barra, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 36, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(datoT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Icono, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(Imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Icono, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(datoT, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Barra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jButton1)
                .addGap(62, 62, 62))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (Encender == 0) {

            try {
                
                arduino.sendData("H");
                Encender=1;
                //Barra.setValue(Barra.getValue()+25);
              
                jButton1.setText("Apagar");
            } catch (Exception ex) {
                
            }

        }
        else if(Encender==1){
            
            try {
                arduino.sendData("L");
                //Barra.setValue(Barra.getValue()+25);
                Encender=0;
                jButton1.setText("Encender");
            } catch (Exception ex) {
               
            }
        
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    
    private void Mensaje(String Dato){
        
        switch(Dato){
            
            case "Enjabonado": 
                Imagen.setIcon((new ImageIcon(IconoEnjabonado.getImage().getScaledInstance(Imagen.getWidth(),Imagen.getHeight(),Image.SCALE_SMOOTH))));
                Barra.setValue(Barra.getValue()+23);
                EnjabonadoL.setBackground(Color.red);
                //EnjabonadoL.setBackground(Color.green);
            break;
            case "Lavado": 
                Imagen.setIcon((new ImageIcon(IconoLavado.getImage().getScaledInstance(Imagen.getWidth(),Imagen.getHeight(),Image.SCALE_SMOOTH))));
                EnjabonadoL.setBackground(Color.green);
                Barra.setValue(Barra.getValue()+23);
                //Icono.setIcon((new ImageIcon(Usuario.getImage().getScaledInstance(Icono.getWidth(),Icono.getHeight(),Image.SCALE_SMOOTH))));
                //EnjabonadoL.setBackground(Color.gray);
                CepilladoL.setBackground(Color.red);
                //EnjabonadoL.setBackground(Color.green);5
            break;
             case "Enjuagado": 
                 Imagen.setIcon((new ImageIcon(IconoEnjuagado.getImage().getScaledInstance(Imagen.getWidth(),Imagen.getHeight(),Image.SCALE_SMOOTH))));
                CepilladoL.setBackground(Color.green);
                Barra.setValue(Barra.getValue()+23);
                //EnjabonadoL.setBackground(Color.gray);
                DesaguadoL.setBackground(Color.red);
                //EnjabonadoL.setBackground(Color.green);5
            break;
            
             case "Secado": 
                 Imagen.setIcon((new ImageIcon(IconoSecado.getImage().getScaledInstance(Imagen.getWidth(),Imagen.getHeight(),Image.SCALE_SMOOTH))));
                DesaguadoL.setBackground(Color.green);
                Barra.setValue(Barra.getValue()+23);
                //EnjabonadoL.setBackground(Color.gray);
                SecadoL.setBackground(Color.red);
                //EnjabonadoL.setBackground(Color.green);5
            break;
            
            case "Finalizado": 
                Imagen.setIcon((new ImageIcon(IconoFinalizado.getImage().getScaledInstance(Imagen.getWidth(),Imagen.getHeight(),Image.SCALE_SMOOTH))));
                SecadoL.setBackground(Color.green);
                Barra.setValue(Barra.getValue()+8);
                //EnjabonadoL.setBackground(Color.gray);
                finalidadoL.setBackground(Color.green);
                Toolkit.getDefaultToolkit().beep();
                JOptionPane.showMessageDialog(null,"Proceso de lavado Finalizado");
                //EnjabonadoL.setBackground(Color.green);5
            break;
            
            case "Avanzando":
               Imagen.setIcon((new ImageIcon(IconoAvanzar.getImage().getScaledInstance(Imagen.getWidth(),Imagen.getHeight(),Image.SCALE_SMOOTH)))); 
            break;
                
            
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_copia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_copia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_copia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_copia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana_copia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar Barra;
    private javax.swing.JLabel CepilladoL;
    private javax.swing.JLabel DesaguadoL;
    private javax.swing.JLabel EnjabonadoL;
    private javax.swing.JLabel Icono;
    private javax.swing.JLabel Imagen;
    private javax.swing.JLabel SecadoL;
    private javax.swing.JLabel cepillado;
    private javax.swing.JLabel datoT;
    private javax.swing.JLabel desaguado;
    private javax.swing.JLabel ejabonado;
    private javax.swing.JLabel finalidadoL;
    private javax.swing.JLabel finalizado;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel secado;
    // End of variables declaration//GEN-END:variables
}
